issueOpenedReply: 'Thanks for opening this issue!'
prOpenedReply: 'The ${preview} will be available after the CI is complete'
previewUrl: 'https://xxx-preview-${pull_num}.xx.com'
compoents:
  table: chenc
